spring.application.name=qually
# Database Connection
spring.datasource.url=jdbc:mariadb://localhost:3306/qually
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.active=dev
